### ISSUE TITLE
I can't execute `jupyter-book build .`

### ISSUE THREAD

**Issue by yukina-t156** [Jij-Inc/Qamomile#73]
Hello. I found some typo and try to contributing this project's document.
It was very simple fix, but I can't build the docs and check the fix works well.

## Environment
- Mac mini 2023 (Apple M2 Pro)

## Problem
I'm trying to setup following [this guideline](https://github.com/Jij-Inc/Qamomile/blob/main/docs/contribute.md),
but `jupyter-book build .`command failed with below error. (Personal information is masked.)

```
Extension error:
Could not import extension autoapi.extension (exception: No module named 'autoapi.extension')
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoapi.extension'
```

I thought the poetry environment has autoapi, but doesn't it? Or, do I have to setup something other than jupyter-book?
Or, is it my locally problem?
Sorry for the basic question. Replies can be in either Japanese or English.

**Comment by yukina-t156** [comment]
I send the all outputs when I did `jupyter-book build .` just in case
```
%jupyter-book build .         
Running Jupyter-Book v1.0.2
Source Folder: /Users/xxx/Qamomile/docs
Config Path: /Users/xxx/Qamomile/docs/_config.yml
Output Path: /Users/xxx/Qamomile/docs/_build/html
Running Sphinx v7.4.7
loading translations [en]... done

Extension error:
Could not import extension autoapi.extension (exception: No module named 'autoapi.extension')
Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sphinx/registry.py", line 453, in load_extension
    mod = import_module(extname)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoapi.extension'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/jupyter_book/sphinx.py", line 114, in build_sphinx
    app = Sphinx(
          ^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sphinx/application.py", line 253, in __init__
    self.setup_extension(extension)
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sphinx/application.py", line 429, in setup_extension
    self.registry.load_extension(self, extname)
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sphinx/registry.py", line 456, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension autoapi.extension (exception: No module named 'autoapi.extension')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxx/.pyenv/versions/3.11.0/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/jupyter_book/cli/main.py", line 317, in build
    builder_specific_actions(
  File "/Users/xxx/.pyenv/versions/3.11.0/lib/python3.11/site-packages/jupyter_book/cli/main.py", line 528, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError: 
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================
```

**Comment by Jacomichi** [comment]
Thank you for your issue!
Contributions to this project are welcome.

I have not been able to reproduce this issue on my local.
I think it's because you haven't been able to create a poetry environment  or work at the poetry environment.
So, please try the following commands.

At `Qamomile` directory, create a poetry environment with the following command, 
```bash
poetry install
poetry shell
```
and can you try it again.
```bash
cd docs
jupyter-book build .
```

**Comment by yukina-t156** [comment]
I resolved this problem.

When I execute `poetry shell`, this message was shown.
```
<username>@docs%poetry shell    
Virtual environment already activated: /Users/username/Library/Caches/pypoetry/virtualenvs/qamomile-9Bm9GSko-py3.11
```
I did `jupyter-book build .` after this immediately, the error I mentioned has occurred.

Then, it looks that I was not in the virtual env I activated, so I did this:
```
<username>@docs %source /Users/username/Library/Caches/pypoetry/virtualenvs/qamomile-9Bm9GSko-py3.11/bin/activate
(qamomile-py3.11)<username>@docs %
```
Then, `jupyter-book build .` was successful.

@Jacomichi
Thank you for your kindness. I'll close this issue because it is resolved.
See you later in PR, maybe.

**Comment by yukina-t156** [comment]
It resolved 👍
